### ISSUE TITLE
overall content architecture feedback

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/code4recovery.github.io#3]
home and projects are essentially duplicates, and they will get out of sync. we should have one or the other

TSML and TSML UI should be under a heading “Demos”

let’s remove the Join page and instead make it a sidebar on the side of every non-demo page (removing the middle paragraph)

**Comment by FlipperPA** [comment]
Should we make this a single-page site for now?

**Comment by joshreisner** [comment]
@FlipperPA i like the way you're thinking, but i think there's too much content for that currently

**Comment by petermixt** [comment]
> 

Sidebar... Left or right side?  needs to be assigned at the page level.

**Comment by joshreisner** [comment]
thanks! this is done now
