### ISSUE TITLE
footer feedback

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/code4recovery.github.io#4]
code for recovery twice in the left column

can we link the email

github logo? (not priority)

remove "built with generatepress"

dynamic year

**Comment by petermixt** [comment]
By using a licensed version of the Generate template these issues are all covered. I have a 500 use license which can be used until I die - as it auto renews with my projects.  I can donate it.

**Comment by petermixt** [comment]
licensed version added

**Comment by joshreisner** [comment]
thanks! i added the github logo and i think we're good now. if we care we can do a dynamic year next january
