### ISSUE TITLE
about, projects, documentation

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/code4recovery.github.io#6]
about
* let’s delete this page, at least until we think of something good to put here
* if not, let’s take out the paragraph about me since tim r is the founder

projects
* let’s delete this page since it duplicates home

documentation
* again, let’s take out this page until we have something good to put
* i was thinking perhaps "tutorials" could be renamed "documentation" to replace this page

**Comment by petermixt** [comment]
about

    let’s delete this page, at least until we think of something good to put here
    if not, let’s **take out the paragraph** about me since tim r is the founder - DONE

projects

    let’s delete this page since it duplicates home - DONE

documentation

    again, let’s take out this page until we have something good to put - DONE
    i was thinking perhaps "tutorials" could be renamed "documentation" to replace this page
