### ISSUE TITLE
tutorials

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/code4recovery.github.io#7]
maybe rename this to documentation?

people should not actually email info@, they should get help on github. could we have a sidebar box in addition to “join us” called “get help” on the side of the TSML help page that sends you to the TSML Github discussions?

refer to it as “12 Step Meeting List” in the link/title and TSML in the text, not "WordPress plugin"

TSML: change the “meeting guide app” link to https://www.aa.org/meeting-guide-app 

TSML: we also have this FAQ now in three places. it’s fine if it’s here and i like the accordion, but then we should take it down from these two places:

* https://github.com/code4recovery/12-step-meeting-list/wiki/Frequently-Asked-Questions
* https://wordpress.org/plugins/12-step-meeting-list/

TSML: take out “Contributors & Developers” section at the bottom

**Comment by petermixt** [comment]
TSML: take out “Contributors & Developers” section at the bottom - removed
refer to it as “12 Step Meeting List” in the link/title and TSML in the text, not "WordPress plugin" - Done

**Comment by petermixt** [comment]
TSML: change the “meeting guide app” link to (https://www.aa.org/meeting-guide-app) ???

**Comment by joshreisner** [comment]
on the TSML tutorial page it links to meetingguide.org…

**Comment by petermixt** [comment]
About adding sidebar info...  Much info can be added. A preference of left or right side? As this is set on each page.

**Comment by joshreisner** [comment]
thanks! i think right side, since the Join Us content is sort of secondary info

**Comment by joshreisner** [comment]
sidebar looks great. i did the remaining stuff on here, incl making the sidebar have a dynamic date
