### ISSUE TITLE
code4recovery.org is down

### ISSUE THREAD

**Issue by rockridgefellowship** [code4recovery/code4recovery.github.io#8]
Hey there -- wasn't sure where to post this, but: As of ~2:55pm pacific, code4recovery.org has a Wordpress critical issue. Folks are probably aware, but thought I'd say something.

**Comment by tim-rohrer** [comment]
Thank you. We are aware, but we have a little access control issue.

Hopefully we'll get the issue resolved soon. 

In the meantime, if you were looking for help, please visit the appropriate repo. If don't know which is the correct one, give me a summary of what you need and I'll get you pointed in the right direction.

**Comment by tim-rohrer** [comment]
The site is back up.

**Comment by rockridgefellowship** [comment]
Very cool! Thanks for the word :)
